sudo: false
language: python
branches:
  only:
  - master
cache:
  directories:
  - $HOME/.cache
install:
- pip install --upgrade pip wheel virtualenv
- pip install nox-automation codecov
- npm install
script:
- nox -s lint freeze js;
after_script:
- codecov
